### ISSUE TITLE
Problem enabling line numbers with minimal set up

### ISSUE THREAD

**Issue by spluque** [jupyter/jupyter-sphinx#142] opened 2020-07-24 16:26 UTC
I've requested feedback on [SO](https://stackoverflow.com/questions/63057352/jupyter-sphinx-linenos-option-does-not-have-any-effect) about this problem.  I'm not sure if it's a bug, but I'm reposting the set up here:

1. Create the simplest Sphinx project via sphinx-quickstart in an empty root directory
2. Leaving everything at default
3. Add "jupyter_sphinx" to the extensions list in conf.py
4. Add a simple block of Python code to index.rst as per the extension's documentation:

```
.. jupyter-execute::
   :linenos:

   print('foo')
   print('bar')
   print('baz')
```

5. Do `make html` at the root dir

The resulting index.html does not show any line numbers.  I've tried enabling the configuration options `jupyter_sphinx_linenos` and `jupyter_sphinx_continue_linenos` to no effect.  What is missing here?

`jupyter_sphinx` version -> 0.2.4

**Comment by seanpue** [comment] 2020-07-24 16:46
I answered on SO.  I can't reproduce. The problem may be that you need to add ``extensions = ["jupyter_sphinx.execute"]`` in ``conf.py`` not just ``"jupyter_sphinx"``.

**Comment by spluque** [comment] 2020-07-24 17:00
@seanpue doing that gives a warning:

> WARNING: while setting up extension jupyter_sphinx.execute: `jupyter-sphinx` was initialized with the `jupyter_sphinx.execute` sub-module. Replace this with `jupyter_sphinx`. Initializing with `jupyter_sphinx.execute` will be removed in version 0.3

and still results in missing line numbers.

**Comment by seanpue** [comment] 2020-07-24 17:53
Ok, sorry @spluque , I was using 2.3. I am also now not seeing the linenos in 2.4.  I can take a look at the code over the weekend if someone doesn't get to it earlier.

**Comment by seanpue** [comment] 2020-08-03 19:45
Hey sorry @spluque  I can't look at this now. Tests should not be passing in 2.4, and this should be marked as a bug. I am tagging some of the developers:  @akhmerov @jbweston @choldgraf   I will check back in when I have some time, but it will take a while. There have been changes to the code over the last few months that I have not been following very closely, so I am not sure where this bug fits into those.

**Comment by akhmerov** [comment] 2020-08-27 10:45
Yeah, this should be easy enough to fix. We now wrap `literal_block` inside a `JupyterInputCell`, and the fix just amounts to pushing everything related to line numbers down to the literal_block.

**Closed** 2020-08-27 12:51 UTC
