### ISSUE TITLE
pandas table overflow

### ISSUE THREAD

**Issue by chenboshuo** [jupyter/jupyter-sphinx#210] opened 2022-08-12 03:32 UTC
when I show tables use this extension, the columns overfolw:
![image](https://user-images.githubusercontent.com/43953268/184279773-a0c4668e-5871-49a5-9d24-b1901ab86b5b.png)

In jupyter, the output is
![image](https://user-images.githubusercontent.com/43953268/184279873-afb42093-fa3c-422c-8d39-1ada0a5fa571.png)
We see it was handled by ba scrollbar.

Could you help me to solve this issue? Thanks you for your attention.

**Comment by akhmerov** [comment] 2022-08-12 08:25
Can you please provide a minimal reproducible example (what to put in conf.py and into the document)?

**Comment by ryandvmartin** [comment] 2022-09-09 13:19
We resolved this issue by adding the following css to our `_static/custom.css`

```
div.jupyter_container .output {
  overflow-x: auto;
}
```

**Comment by 12rambau** [comment] 2023-12-05 10:36
This issue is usually related to the theme you are using in your documentation. Your solution will be very useful for community members who face the same thing and can't wait for the theme patch. 

closing as the problem is not coming from here.

**Closed by 12rambau** 2023-12-05 10:36 UTC
