### ISSUE TITLE
Output of `?` or `??` is not displayed

### ISSUE THREAD

**Issue by Peque** [jupyter/jupyter-sphinx#194] opened 2022-01-16 21:00 UTC
In IPython, you can use `?` or `??` to display information about the object like the docstring, signature and type:

```ipython
In [2]: print??
Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method
```

However, in Jupyter this information is rendered in a box at the bottom instead of bellow the code cell.

![Screenshot from 2022-01-16 20-24-57](https://user-images.githubusercontent.com/526577/149677819-e439f4a5-4fcf-4adf-b5a3-70e09a47412a.png)

This means code like this:

```rest
.. jupyter-execute::

    print??
```

Will not render any output in the documentation.

Is this expected? Would it make sense to implement support for showing this type of information bellow the code cell in the documentation?

**Comment by akhmerov** [comment] 2022-01-16 21:07
This is a duplicate of #193, which is in turn an upstream issue https://github.com/jupyter/nbclient/issues/196

**Closed by akhmerov** 2022-01-16 21:07 UTC
