### ISSUE TITLE
An error in one jupyter-sphinx document leads to all documents being rebuilt

### ISSUE THREAD

**Issue by jbweston** [jupyter/jupyter-sphinx#31] opened 2019-04-30 10:04 UTC
Currently if there are 3 documents that have `jupyter-execute` directives in them, and if an error occurs in 1 document (i.e. uncaught error in one of the cells) then this causes all 3 documents to be rebuilt next time sphinx is run. This can be problematic when documents take a significant time to execute.

Can perhaps be mitigated by #30.

**Comment by akhmerov** [comment] 2019-04-30 11:25
An alternative solution would be to investigate how sphinx performs caching. OTOH implementing caching based purely on the documentation sources is also rather dangerous because the evaluation result may change with the external dependencies.

**Comment by jbweston** [comment] 2019-05-01 07:34
> OTOH implementing caching based purely on the documentation sources is also rather dangerous because the evaluation result may change with the external dependencies.

But this is what happens now anyway. If the docs were previously built successfully and `a_document.rst` changes then only that one is re-executed now. It just sucks that if that execution fails then the next time we run sphinx *all* the docs are re-executed; it seems that sphinx failing somehow invalidates the whole cache.

**Comment by moorepants** [comment] 2019-12-25 16:02
I am building up some documentation that has multiple pages that take 10 to 30 seconds to build each and it isn't apparent to me that they are ever cached. It would be nice if nothing changed in the source (regardless of dependencies) that the page would not be rebuilt.

> is also rather dangerous because the evaluation result may change with the external dependencies

I think that this is an issue that is not needed to be addressed. A user can always run `make clean` before a build if they need a fresh build for changes in dependencies.

**Comment by akhmerov** [comment] 2020-05-06 21:02
I have confirmed that with #107 merged only the changed files are re-executed :tada:

Let me know if you still see failures.

**Closed by akhmerov** 2020-05-06 21:02 UTC
